export const SET_INITIAL = 'SET_INITIAL'
export const SET_MONTHLY = 'SET_MONTHLY'
export const SET_INTEREST = 'SET_INTEREST'
export const SET_INTERVAL = 'SET_INTERVAL'
export const GET_RESULTS = 'GET_RESULTS'
